name: PR labeler
on:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
